server:
  port: 8766

spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:import.sql
    url: jdbc:h2:mem:mydb
    username: qwerty
    password: qwerty